spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres