spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
#    drop-first: true
#  jpa:
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
fr:
  committer:
    task:
      frequency: PT10M
      retryLimit: 5