spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
    drop-first: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#Quartz
fr:
  committer:
    job:
      frequency: PT1M